### PR TITLE
Update test.yaml

### PR DESCRIPTION
**Pull request by OlegP-andrew**
Removing testing for non-redis databases

### CODE REVIEW

**Review by kayliny02 — APPROVED** [review]
LGTM!

**Comment by eichel-choi** [comment]
Lookgs good to me!

**Review by eichel-choi — COMMENTED** [review]
Looks good to me!

**Review by JamieC2002 — COMMENTED** [review]
LGTM!

**Comment by ihindi1111** [comment]
Looks good!

**Pull request merged**
