### PR TITLE
Sanity check for src/topics/create.js

### LINKED ISSUE #42: Add sanity checks for src/topics/create.js
Need to add sanity checks for each function in src/topics/create.js

Document the type signature in code comments
Assert function parameter types in the body
Assert function return types in the body or write unit tests that execute and validate that the function returns the expected type

Effort: Low
Dependencies: File needs to be completed with modifications
Acceptance criteria: Passes npm run lint and npm run test

### PR DESCRIPTION
**Pull request by ihindi1111**
Added sanity-checks for file src/topics/create.js
Did not translate to Typescript, but need to make JS file type safe with type checks

Added the following sanity-checks:
- Document the type signature in code comments
- Assert function parameter types in the body
- Assert function return types in the body or write unit tests that execute and validate that the function returns the expected type.

Made sure npm lint and npm run test passed

Resolves #42

### CODE REVIEW

**Review by kayliny02 — CHANGES_REQUESTED** [review]
For the functions that return void, add that to the type signatures at the top of each function

**Review by kayliny02 — APPROVED** [review]
Thanks for making the changes! Ready to merge :)

**Review by JamieC2002 — APPROVED** [review]
LGTM, good work!

**Review by OlegP-andrew — APPROVED** [review]
Sanity checks looks correct, passes automated tests, should be good to merge!

**Pull request merged**
