### PR TITLE
Endorsing Answers Feature

### LINKED ISSUE #7: Endorsing Answers Backend
Feature: Allow instructors to support answers to questions, to indicate that the answer is correct. Modify the upvote privilege by only allowing instructors or administrators to endorse.
Effort: Low
Dependencies: none
Acceptance Criteria: Instructors can select answers and have an option to endorse them.

Responsibilities:
Front end: Kaylin
Back end: Jamie

### PR DESCRIPTION
**Pull request by kayliny02**
Front-end changes:
- Replaced upvote downvote system with endorse option (kept count)
- Endorsed posts will have a green endorsed indicator at the top of the post
- Replaced vote count to endorsements count in the list of topics page

Back-end changes:
- Instructors / Admins are able to endorse answers. Repurposed the upvote feature to enable Endorsement.
- Students will not be able to endorse answers.
- Tests were added to check endorsement, and tests related to voting have been removed.

Resolves #7 and #23 and #26

### CODE REVIEW

**Review by ihindi1111 — COMMENTED** [review]
Resolved conflicts with both coding and lint errors

**Comment by OlegP-andrew** [comment]
Changes looking good, the instructor checking mechanism was already tested in the #25 . You should be able to safely merge.

**Review by OlegP-andrew — APPROVED** [review]
Changes looking good, the instructor checking mechanism was already tested in the #25  . You should be able to safely merge.

**Review by eichel-choi — APPROVED** [review]
This looks good to me! You brought consistency in the code by removing the blocks and integrating the rest of the code into the bigger block

**Review by ihindi1111 — APPROVED** [review]
Resolved conflicts with both coding and lint errors

**Pull request merged**
